# Use the official MySQL base image
FROM mysql:latest
RUN apt-get update && apt-get install -y mysql-client

# Optionally, set environment variables or configurations for MySQL
# ENV MYSQL_ROOT_PASSWORD=root_password
# ENV MYSQL_DATABASE=my_database
# ENV MYSQL_USER=my_user
# ENV MYSQL_PASSWORD=my_password

# Expose the MySQL port (default is 3306)
EXPOSE 3306
